<a href="https://colab.research.google.com/github/MarcAstner/Dig-Bata/blob/master/GravWaves.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from scipy import integrate 
from scipy.misc import derivative
from math import *

In [0]:
c = 299792458
G = 6.67430 * 10**(-11)
Ms = 1.989 * 10**30

In [0]:
def S(x):
  return (9 *10**(-46))*((4.49*x**(-56))+(0.16*x**(-4.52))+0.52+(0.32*x**2))

In [0]:
def I(x):
  return ((x**(-7/6)/S(x)))

In [0]:
#observables
m1 = 30 *Ms
m2 = 30 *Ms
M = m1 + m2
v = (M*x*np.pi)**(1/3)
psi = 1
eta = (m1*m2)/(M**2)
N_pta = 4
tc = 1

In [0]:
array = []
array.append(1)#a0
array.append(0)#a1
array.append((20/9)*((743/336)+((11/4)*eta)))#a2 ! write it as an function of eta
array.append(-16*np.pi)#a3
array.append((10)*((3058673/1016064)+((5429/1008)*eta)+((617/144)*eta**2)))#a4

def psi_x(x):
  sum_k = 0
  for k in range(len(array)):
        sum_k += array[k]*v**2
        return (2*np.pi*x*tc)-(psi)-(np.pi/4)+(3/(128*eta*v**5))*sum_k
print(array)

def h_x(x):
    psi = psi_x(x)
    h_x = A*x**(-7/6)*np.exp(1j * psi)
    return h_x

print(h_x(x))

[1, 0, 6.441798941798942, -50.26548245743669, 46.245886085915856]
(-1.5487358105400252e-24-7.105658479664057e-24j)


In [0]:
#calculating A
x = 150 #frequency
SNR = 10
fs = 40 #lower limit
fu_conv = (c**3)*(1/G) #conversion needed because of simplyfing G and c to 1 
fu = ((6**(3/2))*np.pi*M)**(-1)*fu_conv #upper limit

A2 = SNR/(4*(integrate.quad(I, fs , fu)[0])) #gives out an array; only first index is used for further calculations

A = np.sqrt(A2)

print(A) #hertz

2.5145233326594496e-21


In [0]:
def derive(function, value):
    h = 0.00000000001
    top = function(value + h) - function(value)
    bottom = h
    slope = top / bottom
    return float("%.3f" % slope)

In [0]:
def R():
  

In [0]:
for i in range ():
  for j in range ():
    result = 4*(integrate.quad(R, fs, fu))

In [0]:
mat = np.matrix ([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])

f_matrix =np.zeros ((4,4), dtype = int)
print (f_matrix)
print(mat)
print(mat.diagonal(0))



[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  5 10 15]]
